### ISSUE TITLE
Filtering result count changes when user click on 'Update Results' button again and again

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#14]
## Target URL

https://frontend.app.cloud.gov/

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User
3. Click Search button
4. Enter 'Branch of service' as US ARMY
5. Click 'Update Results' button
6. Check the result count
7. Click 'Update Results' button again
8. Check the result count
9. Click 'Update Results' button again
10. Check the result count

## Actual Result(s)

- Filtering result count changes when user click on 'Update Results' button again and again

## Expected Result(s)

- Must display the same count

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/VEDhRkT7P

**Comment by ramillim** [comment]
The actual bug is that the date selected in the filter kept changing due to an improper usage of the javascript Date object that resulted in a conversion to the browser's local time. It would make the date decrease by one day every time you ran the search. I fixed this in PR #48 while working on another issue.
