### ISSUE TITLE
[$50] 'Salutes' count is not updating when user click on 'Salute' button

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#29]
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Admin]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Stories' section and click on 'Read more' from one of the stories
8. Check the 'Salutes' count > 489
9. Click on the 'Salute' button
10. Check the 'Salutes' count > 489

## Actual Result(s)

- 'Salutes' count is not updating when user click on 'Salute' button

## Expected Result(s)

- Must increase the count of the 'Salutes' when user click on the 'Salute' button

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

![24](https://user-images.githubusercontent.com/4592712/41750229-66ddb40e-7580-11e8-9dee-36d626a90759.jpg)

**Comment by ramillim** [comment]
@dustinWeaver could you add a task dependency for this issue on the rest-api project? of the 3 (reads, salutes, and shares), only salutes is even implemented on backend.

This issue will be blocked until that's completed.

**Comment by ramillim** [comment]
In the meantime, this one also has a design decision:
I think that when this is implemented, clicking on salute should just increment the number by 1 instead of getting the actual number from the backend. I think that will make it snappier instead of having to wait for the response and avoid confusion when the number goes up by more than one because other people saluted at the same time.

When the post is reloaded with a fetch from the server, it can then provide whatever the current number is (or cached number depending on how it is implemented).

**Comment by dustinWeaver** [comment]
Thanks @ramillim, I've added the issue on the [rest-api repo](https://github.com/topcoderinc/va-online-memorial-rest-api/issues/2).

I'll tag this as "phase 2" as well.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069624 has been created for this ticket.

**Comment by dustinTopcoder** [comment]
Contest https://www.topcoder.com/challenges/30069624 has been updated - the new changes has been updated for this ticket.

**Comment by ksmacleod99** [comment]
Resolved in PR #90
