### ISSUE TITLE
Search does not work correctly

### ISSUE THREAD

**Issue by dustinWeaver** [topcoderinc/va-online-memorial-frontend#4]
When using the search function, it seems to sporadically bring back results. 

Video here: https://www.screencast.com/t/OBvuX3PK7a0j

**Comment by dustinWeaver** [comment]
Steps to reproduce:

1. Go to https://frontend.app.cloud.gov/
1. On the search bar, search for a common name (Example: "Smith")
1. Observe search results behavior

**Comment by ramillim** [comment]
@dustinWeaver I suspect that the response issue may be related to the latency between when the user types and when the query response is returned and rendered. The UI currently sends a request each type the state changes on the form.

Now if you take a look at how this shows up on the console of me typing "Weaver"
![image](https://user-images.githubusercontent.com/3946035/41617671-1e655860-73cf-11e8-9bc8-397a6628ae2e.png)

The GET responses are returning in order of completion from the server (since they are async requests) and then rendering the results accordingly. Since "We" returned the latest (computationally more expensive -- I suspect that "W" might've taken longer as well, but the request was fired off first so it returned before "We"), it rendered last.

One solution I am thinking of is to make submission of the form state for the search bar explicit (it only submits when you hit enter/click on the button). Are there any design restrictions on this form that require it to update as you type?

**Comment by dustinWeaver** [comment]
I think it was designed with the dynamic search in mind as it was flashy, but if it doesn't work, then doing it the way you suggest would be great.  

Functionality over form!

**Comment by ramillim** [comment]
I can probably figure out a way to preserve dynamic search as well. It's pretty common, so I can look into what patterns are used to invalidate all but the most recent request when rendering the results.

**Comment by dustinWeaver** [comment]
@ramillim, any update?

cc: @ksmacleod99

**Comment by ramillim** [comment]
@dustinWeaver I only had an opportunity to do a preliminary look into this. Basically, this would need to use the pattern described here for canceling duplicate requests: https://redux-resource.js.org/recipes/canceling-requests as well as implement debouncing on the search box input.

I have limited experience working with Redux, so this would take me a little longer to do. I can work through this much much later tonight, but if you need it done sooner, you can reassign :)

**Comment by dustinWeaver** [comment]
@ramillim, if you can take a look at it tonight and let us know what you think by tomorrow, that's ok.

**Comment by ramillim** [comment]
@dustinWeaver Cool. I did push up this commit that enables cancellation of the other requests and it is working, but I want to think through this more thoroughly such as is there a better way to do this than adding another library (bluebird), should I actually be performing the cancellation 
as a redux action, etc. 

But if we just want working, this works :)
https://github.com/ramillim/va-online-memorial-frontend/commit/6dab02efba62553f004058b9fb8fd4ed4ee27042

**Comment by dustinWeaver** [comment]
I can wait for you to think it over.  Just let me know by COB tomorrow and we can go from there.
